### ISSUE TITLE
docker-compose.yml for testnet

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-headless#66]
`docker-compose.yml` to connect to the testnet:

```yml
version: "3.9"
services:
  hathor-wallet-headless:
    image: hathornetwork/hathor-wallet-service:v0.4.0-23-g5f45adb
    command: run_node
    ports:
      - "8000:8000"
    environment:
      - HEADLESS_SEED_DEFAULT=PUT YOUR SEED HERE SEPARATED BY SPACES (e.g. nose strong task ...)
      - HEADLESS_NETWORK=testnet
      - HEADLESS_SERVER=https://node1.foxtrot.testnet.hathor.network/v1a/
```
